<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" 
        integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>04 - async-await</title>
</head>
<body class="container-fluid bg-primary p-2">
    <main class="container-fluid bg-white p-2">
        <h1><u>04 - async-await</u></h1>
        <div class="container">
            <pre class="bg-dark text-white p-3">
//add async before any function declaration to treat it as a Promise function:
async function add(x,y) {
    
    if (typeof x !== 'number' || typeof y !== 'number') {
        throw "INVALID NUMBER TYPE";
    }

    return x + y;
}

add(9, 4)
    .then(data => {
        console.log("add() function: Inside Resolve \n\nadd() function: ")
        console.log(data);
    })
    .catch(err => {
        console.log("add() function: Inside Reject")
        console.log("add() function: Something Went Wrong\n\nadd() function:");
        console.log(err);
    })


//---------------------------------------------------------------------------------------------------


//using async-await:    
async function getBitCoinPrice() {
    console.log("getBitCoinPrice(): Starting the getBitCoin Function=>");

    const response=await fetch('https://api.cryptonator.com/api/ticker/btc-usd');
    
    console.log("getBitCoinPrice(): Got the Response from fetch.");

    console.log("getBitCoinPrice(): Now, Parsing response for Data...");
    
    const data = await response.json();
    console.log("getBitCoinPrice(): Parsing Completed.");

    console.log('getBitCoinPrice(): \nCurrent price: ');
    console.log(data.ticker.price);
    console.log("getBitCoinPrice Function completes, ALL DONE!!");

}

//calling getBitCoinPrice() function
getBitCoinPrice()
    .then(() => {
        console.log("getBitCoinPrice(): Resolved");
    })
    .catch(err => {
        console.log("getBitCoinPrice(): AAAHHHH! ERROR\n\ngetBitCoinPrice(): ");
        console.log(err);
    })

// Below will be printed first because 
// of the delay happening in getting the response from Promises
console.log("AFTER FUNCTION");
console.log("AFTER FUNCTION");
console.log("AFTER FUNCTION");
console.log("AFTER FUNCTION");

            </pre>
        </div>
        <div class="container">
            <pre class="bg-dark text-white p-3">
                Great. Hurray! 
                You have completed Lecture-08
                You can go back to HomePage and proceed to Lecture-09
                Thank You.
            </pre>
        </div>
    </main>
    <footer class="p-3">
        <p class="d-block text-center text-white">Next: 
            <a class="text-white" href="https://sidp919.github.io/Web-Development/">Go back to Web Development Homepage</a></p>
    </footer>
    <script>
//add async before any function declaration to treat it as a Promise function:
async function add(x,y) {
    
    if (typeof x !== 'number' || typeof y !== 'number') {
        throw "INVALID NUMBER TYPE";
    }

    return x + y;
}

add(9, 4)
    .then(data => {
        console.log("add() function: Inside Resolve \n\nadd() function: ")
        console.log(data);
    })
    .catch(err => {
        console.log("add() function: Inside Reject")
        console.log("add() function: Something Went Wrong\n\nadd() function:");
        console.log(err);
    })


//---------------------------------------------------------------------------------------------------


//using async-await:    
async function getBitCoinPrice() {
    console.log("getBitCoinPrice(): Starting the getBitCoin Function=>");

    const response=await fetch('https://api.cryptonator.com/api/ticker/btc-usd');
    
    console.log("getBitCoinPrice(): Got the Response from fetch.");

    console.log("getBitCoinPrice(): Now, Parsing response for Data...");
    
    const data = await response.json();
    console.log("getBitCoinPrice(): Parsing Completed.");

    console.log('getBitCoinPrice(): \nCurrent price: ');
    console.log(data.ticker.price);
    console.log("getBitCoinPrice Function completes, ALL DONE!!");

}

//calling getBitCoinPrice() function
getBitCoinPrice()
    .then(() => {
        console.log("getBitCoinPrice(): Resolved");
    })
    .catch(err => {
        console.log("getBitCoinPrice(): AAAHHHH! ERROR\n\ngetBitCoinPrice(): ");
        console.log(err);
    })

// Below will be printed first because 
// of the delay happening in getting the response from Promises
console.log("AFTER FUNCTION");
console.log("AFTER FUNCTION");
console.log("AFTER FUNCTION");
console.log("AFTER FUNCTION");
    </script>
</body>
</html>